name: Pipeline Backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flask
    - name: Pylint
      run: pylint *.py
    - name: Pytest
      run: pytest test_*.py
